In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.convert_to_tensor(np.ones([1,2]))

<tf.Tensor: shape=(1, 2), dtype=float64, numpy=array([[1., 1.]])>

In [4]:
tf.convert_to_tensor(np.zeros([1,2]))

<tf.Tensor: shape=(1, 2), dtype=float64, numpy=array([[0., 0.]])>

In [5]:
tf.convert_to_tensor([1,2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [6]:
tf.convert_to_tensor([1,2.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [7]:
a = tf.zeros([2,2,3])
a

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [8]:
tf.zeros_like(a)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [9]:
tf.fill([2,3],8)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[8, 8, 8],
       [8, 8, 8]])>

In [10]:
tf.random.normal([2,2],mean=1,stddev=2)  # normal正态分布，mean数学期望，stddev方差

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.5420135,  2.139884 ],
       [ 3.1196334,  1.1482546]], dtype=float32)>

In [11]:
tf.random.truncated_normal([2,3],mean=1,stddev=2)  # 一定置信区间的正态分布的随机取样

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 3.1538587,  2.710074 ,  3.6418643],
       [ 2.204836 , -2.6789358,  2.7724695]], dtype=float32)>

In [12]:
tf.random.uniform([2,2],minval=0,maxval=1)  # 平均取值

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.15961051, 0.28825128],
       [0.31946588, 0.3528775 ]], dtype=float32)>

In [13]:
idx = tf.range(10)
idx = tf.random.shuffle(idx)

a = tf.random.normal([10,784])
b = tf.random.uniform([10],maxval=10,dtype=tf.int32)
#print(b)

a = tf.gather(a,idx)
b = tf.gather(b,idx)

#print(a)
print(b)

tf.Tensor([4 4 8 3 1 2 7 7 0 0], shape=(10,), dtype=int32)


In [14]:
tf.constant(1)  # 标量

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [15]:
tf.constant([1])  # 向量

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>

In [16]:
a = tf.random.normal([4,28,28,3])
b = tf.reshape(tensor=a,shape=[4,28*28,3])
b.shape,b.ndim

(TensorShape([4, 784, 3]), 3)

In [17]:
a = tf.random.normal([4,28,28,3])
b = tf.transpose(a=a,perm=[3,2,1,0])  # transpose作用：置换a的维度为指定维度
b.shape

TensorShape([3, 28, 28, 4])

In [18]:
a = tf.random.normal([4,28,28,3])
b = tf.expand_dims(a,axis=2)  # 扩展维度
b.shape

TensorShape([4, 28, 1, 28, 3])

In [19]:
a = tf.random.normal([1,4,28,28,3])
b = tf.squeeze(input=a,axis=0)  # 只能减少该维度为1的维度
b.shape

TensorShape([4, 28, 28, 3])