In [1]:
import tensorflow as tf
import numpy as np

In [10]:
# 合并与分割
a = tf.random.normal(shape=[2,2,3])
b = tf.random.normal(shape=[1,2,3])

# 合并  (其合并维度可以不一样，但是其他维度的大小必须相等)
c = tf.concat(values=[a,b],axis=0)
print(c.shape)

(3, 2, 3)


In [21]:
a = tf.ones([2,2,3])
b = tf.ones([2,2,3])

# 合并  （其合并并在指定维度上创造出新的维度，原维度必须相同，指定维度的范围为原维度的数量上加一）
c = tf.stack(values=[a,b],axis=0)
c

<tf.Tensor: shape=(2, 2, 2, 3), dtype=float32, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)>

In [38]:
a = tf.convert_to_tensor(np.random.randint(low=1,high=9,size=[2,4,35,8]))

# 分割  （分割指定的维度，返回指定被分割维度的新生成列表，列表里的每一个元素存放一个tensor，num必须与指定维度的大小相同）
b = tf.unstack(value=a,num=8,axis=3)
b

[<tf.Tensor: shape=(2, 4, 35), dtype=int32, numpy=
 array([[[6, 7, 3, 6, 5, 8, 7, 5, 1, 4, 8, 2, 2, 3, 8, 5, 5, 1, 1, 3, 8,
          1, 6, 3, 8, 5, 3, 1, 4, 7, 4, 8, 5, 2, 2],
         [2, 5, 6, 4, 8, 5, 6, 7, 3, 7, 2, 7, 2, 5, 6, 2, 6, 3, 5, 6, 7,
          8, 4, 3, 5, 6, 7, 2, 6, 8, 7, 2, 6, 4, 6],
         [4, 7, 8, 7, 3, 5, 3, 6, 4, 1, 3, 5, 4, 8, 2, 4, 3, 5, 8, 8, 7,
          8, 1, 3, 4, 5, 4, 4, 1, 5, 1, 4, 2, 1, 2],
         [1, 7, 1, 1, 8, 1, 7, 1, 7, 8, 1, 3, 8, 8, 1, 6, 1, 1, 3, 3, 1,
          5, 2, 6, 6, 6, 8, 1, 1, 7, 6, 5, 4, 8, 6]],
 
        [[3, 8, 3, 6, 3, 2, 7, 8, 8, 4, 7, 6, 6, 1, 4, 8, 3, 5, 3, 8, 7,
          3, 5, 8, 3, 5, 4, 2, 6, 7, 7, 1, 3, 3, 3],
         [3, 8, 7, 7, 4, 2, 6, 3, 1, 8, 3, 2, 6, 4, 4, 5, 3, 2, 5, 3, 4,
          4, 8, 5, 7, 5, 3, 3, 4, 2, 3, 5, 4, 3, 5],
         [5, 1, 6, 6, 1, 8, 6, 6, 7, 1, 1, 2, 5, 3, 8, 5, 6, 7, 5, 4, 8,
          6, 2, 1, 7, 1, 5, 4, 2, 7, 3, 5, 2, 5, 7],
         [8, 7, 8, 4, 7, 1, 8, 8, 6, 1, 4, 4, 5, 7, 7, 4, 2, 8, 

In [5]:
a = tf.convert_to_tensor(np.random.randint(low=0,high=10,size=[2,4,28,8]))
# 将指定维度切割成指定数量的tensor
# b = tf.split(value=a,num_or_size_splits=4,axis=2)
b = tf.split(value=a,num_or_size_splits=[2,4,8,14],axis=2)
print(b[0].shape)

(2, 4, 2, 8)


In [8]:
a = tf.ones(shape=[2,2])
# norm 范数函数 ord默认为2即为2范数 所有元素平方和的根号
b = tf.norm(tensor=a)
print(b)

b = tf.norm(tensor=a,ord=1,axis=1)
print(b)

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor([2. 2.], shape=(2,), dtype=float32)


In [19]:

b = tf.reduce_min(input_tensor=a)
print(b)
b= tf.reduce_max(input_tensor=a,axis=1)
print(b)
b = tf.reduce_mean(input_tensor=a,axis=0)
print(b)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([9 9], shape=(2,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [2]:
a = tf.convert_to_tensor(np.random.randint(low=0,high=100,size=[4,10]))
# 返回每列数值最大的下标
b = tf.argmax(a,axis=0)
print(a)
print(b)

tf.Tensor(
[[74 17 45  3 33 41 80 71 53 95]
 [61  7 15 11 78 51  8 95 96 43]
 [48 71 31 11 76 30 67 43 44 72]
 [24 52 34  0 71 63 69 44  6  3]], shape=(4, 10), dtype=int32)
tf.Tensor([0 2 0 1 1 3 0 1 1 0], shape=(10,), dtype=int64)


In [12]:
a = tf.random.uniform(shape=[5],maxval=10,minval=0,dtype=tf.int32)
b = tf.random.uniform(shape=[5],maxval=10,minval=0,dtype=tf.int32)
c = tf.equal(a,b)
print(a)
print(b)
c

tf.Tensor([0 5 5 0 9], shape=(5,), dtype=int32)
tf.Tensor([9 2 4 0 0], shape=(5,), dtype=int32)


<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False, False, False,  True, False])>

In [14]:
a = tf.constant([4,2,2,8])
# 去除重复元素，并返回去除后的结果和由于还原的下标列表
b,indexs = tf.unique(a)
print(b)
print(indexs)

tf.Tensor([4 2 8], shape=(3,), dtype=int32)
tf.Tensor([0 1 1 2], shape=(4,), dtype=int32)


In [16]:
a = tf.random.uniform(shape=[2,8],minval=0,maxval=10,dtype=tf.int32)
# 返回排序后数的下标
b = tf.argsort(values=a)
print(b)

tf.Tensor(
[[2 4 5 7 0 6 1 3]
 [0 5 4 7 2 1 3 6]], shape=(2, 8), dtype=int32)


In [16]:
def accuracy(output, target, topk=(1,)):
    maxk = max(topk)
    batch_size = target.shape[0]

    pred = tf.math.top_k(output, maxk).indices
    pred = tf.transpose(pred, perm=[1, 0])
    target_ = tf.broadcast_to(target, pred.shape)
    # [10, b]
    correct = tf.equal(pred, target_)

    res = []
    for k in topk:
        correct_k = tf.cast(tf.reshape(correct[:k], [-1]), dtype=tf.float32)
        correct_k = tf.reduce_sum(correct_k)
        acc = float(correct_k* (100.0 / batch_size) )
        res.append(acc)

    return res

output = tf.random.normal([10,6])
# print(output)
# 将数字非负化，数字在0~1之间  指定维度上的概率和为1
output = tf.math.softmax(output,axis=1)
# print(output)
target = tf.random.uniform([10], maxval=6, dtype=tf.int32)
print('prob:', output.numpy())
pred = tf.argmax(output, axis=1)
print(pred)
print('pred:', pred.numpy())
print('label:', target.numpy())

acc = accuracy(output, target, topk=(1,2,3,4,5,6))
print('top-1-6 acc:', acc)

prob: [[0.07092398 0.45647112 0.28407836 0.0986164  0.07108837 0.01882171]
 [0.09400044 0.633499   0.01791293 0.19099584 0.00937884 0.05421297]
 [0.037146   0.14955747 0.0892282  0.03838715 0.5520713  0.13360992]
 [0.18911383 0.10277313 0.15598328 0.37790042 0.02610186 0.14812753]
 [0.08480476 0.2798715  0.12074472 0.11277805 0.34854317 0.05325782]
 [0.10458001 0.29127485 0.04326278 0.04354617 0.05151158 0.46582457]
 [0.12780125 0.21335086 0.14902811 0.07599062 0.0580873  0.37574187]
 [0.03602464 0.16124883 0.52969116 0.00787041 0.154847   0.11031789]
 [0.08850855 0.34216738 0.11101062 0.22776408 0.05315229 0.17739715]
 [0.04780628 0.56260496 0.05955708 0.04174819 0.12936485 0.15891863]]
tf.Tensor([1 1 4 3 4 5 5 2 1 1], shape=(10,), dtype=int64)
pred: [1 1 4 3 4 5 5 2 1 1]
label: [1 3 3 5 0 2 5 4 1 4]
top-1-6 acc: [30.0, 40.0, 60.0, 70.0, 90.0, 100.0]


In [19]:
a = tf.convert_to_tensor(np.random.randint(low=0,high=10,size=[3,3]))
print(a)
# 参数paddings的顺序上下左右
b = tf.pad(tensor=a,paddings=[[0,1],[1,0]])
print(b)

tf.Tensor(
[[8 1 5]
 [5 2 5]
 [5 3 2]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 8 1 5]
 [0 5 2 5]
 [0 5 3 2]
 [0 0 0 0]], shape=(4, 4), dtype=int32)


In [21]:
a = tf.convert_to_tensor(np.random.randint(low=0,high=10,size=[3,3]))
# 参数multiples的数值为原张量的倍数
b = tf.tile(input=a,multiples=[3,1])
print(a)
print(b)

tf.Tensor(
[[4 0 5]
 [0 3 4]
 [5 0 2]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[4 0 5]
 [0 3 4]
 [5 0 2]
 [4 0 5]
 [0 3 4]
 [5 0 2]
 [4 0 5]
 [0 3 4]
 [5 0 2]], shape=(9, 3), dtype=int32)


In [26]:
a = tf.random.uniform(shape=[10],minval=-5,maxval=20,dtype=tf.int32)
# 将不满足a>=0的值改成0
b = tf.maximum(a,0)
print(a)
print(b)
# 将不满足a<=0的值改成10
b = tf.minimum(a,10)
print(a)
print(b)

b = tf.clip_by_value(a,clip_value_max=9,clip_value_min=0)
print(b)

tf.Tensor([-2 13  2 11  8 19 15  7  0  4], shape=(10,), dtype=int32)
tf.Tensor([ 0 13  2 11  8 19 15  7  0  4], shape=(10,), dtype=int32)
tf.Tensor([-2 13  2 11  8 19 15  7  0  4], shape=(10,), dtype=int32)
tf.Tensor([-2 10  2 10  8 10 10  7  0  4], shape=(10,), dtype=int32)
tf.Tensor([0 9 2 9 8 9 9 7 0 4], shape=(10,), dtype=int32)


In [25]:
a = tf.random.uniform(shape=[10],minval=-5,maxval=20,dtype=tf.int32)
# 把所有的负值都变为0，而正值不变，这种操作被成为单侧抑制。
a = tf.nn.relu(a)
print(a)

tf.Tensor([16 19  0 16  2  9 10  7 19  6], shape=(10,), dtype=int32)


In [39]:
a = tf.random.normal([3,3])
# print(a)
mask = a > 0
print(mask)
# 提取mask为True时的a的值
b = tf.boolean_mask(a,mask)
# print(b)
# 提取True的坐标值
b = tf.where(condition=mask)
c = tf.gather_nd(a,b)
print(c)

A = tf.ones([3,3])
B = tf.zeros([3,3])
# True取A的值，Fasle取B的值
c = tf.where(mask,A,B)
print(c)

tf.Tensor(
[[ True  True False]
 [ True False False]
 [False  True False]], shape=(3, 3), dtype=bool)
tf.Tensor([1.1451882  0.1132425  1.4096942  0.20118167], shape=(4,), dtype=float32)
tf.Tensor(
[[1. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]], shape=(3, 3), dtype=float32)


In [40]:
indecies = tf.constant([[4],[3],[1],[7]])
updata = tf.constant([9,10,11,12])
shape = tf.constant([8])
a = tf.scatter_nd(indecies,updata,shape)
print(a)

tf.Tensor([ 0 11  0 10  9  0  0 12], shape=(8,), dtype=int32)
